import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service — CogniGraph',
}

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-bg text-text">
      <header className="mx-auto flex max-w-3xl items-center justify-between px-6 py-6">
        <Link href="/" className="text-sm font-semibold tracking-tight">
          Cogni<span className="text-accent">Graph</span>
        </Link>
        <Link href="/" className="text-sm text-text-muted transition hover:text-text">
          ← Back home
        </Link>
      </header>

      <main className="mx-auto max-w-3xl px-6 pb-24 pt-4">
        <h1 className="text-3xl font-semibold tracking-tight">Terms of Service</h1>
        <p className="mt-2 text-sm text-text-muted">Last updated: July 2026</p>

        <div className="mt-6 rounded-lg border border-border border-l-2 border-l-signature bg-surface p-4 text-sm text-text-muted">
          This is a starting draft, not legal advice — it should be reviewed
          by a lawyer before it's treated as your binding terms, especially
          the disclaimer and liability sections, given this product
          generates content using third-party AI models.
        </div>

        <div className="mt-10 space-y-10 text-sm leading-relaxed text-text-muted">
          <section>
            <h2 className="text-lg font-semibold text-text">
              1. Acceptance of terms
            </h2>
            <p className="mt-3">
              By creating an account or using CogniGraph, you agree to these
              Terms of Service and our{' '}
              <Link href="/privacy" className="text-accent underline">
                Privacy Policy
              </Link>
              . If you don&apos;t agree, please don&apos;t use the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-text">
              2. What CogniGraph does
            </h2>
            <p className="mt-3">
              CogniGraph is an AI research assistant. Given a query, it
              autonomously plans searches, runs them across the web and any
              documents you upload, critiques its own findings, and produces
              a cited report. It uses third-party AI models and search
              services to do this — see our{' '}
              <Link href="/privacy" className="text-accent underline">
                Privacy Policy
              </Link>{' '}
              for details on which ones.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-text">
              3. AI-generated content — no guarantee of accuracy
            </h2>
            <p className="mt-3">
              Reports, summaries, critiques, citations, and chart data
              produced by CogniGraph are generated by AI models and may
              contain errors, omissions, or fabricated details
              (&quot;hallucinations&quot;). CogniGraph is a research aid, not
              a substitute for verifying information against primary
              sources. You are responsible for checking the accuracy of any
              output before relying on it, publishing it, or citing it
              elsewhere.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-text">
              4. Your account
            </h2>
            <p className="mt-3">
              You&apos;re responsible for keeping your account credentials
              secure and for all activity under your account. You must
              provide accurate information when signing up, whether by email
              or through Google sign-in.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-text">
              5. Your content
            </h2>
            <p className="mt-3">
              You retain ownership of any documents you upload and any
              queries you submit. By uploading a document, you confirm you
              have the right to do so and to have it processed by the
              third-party AI and search services CogniGraph relies on. You
              grant us the limited right to store and process your content
              solely to provide the service to you.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-text">
              6. Acceptable use
            </h2>
            <p className="mt-3">You agree not to:</p>
            <ul className="mt-3 list-disc space-y-2 pl-5">
              <li>
                Upload content you don&apos;t have the right to share, or
                that infringes someone else&apos;s rights.
              </li>
              <li>
                Use CogniGraph to generate or spread content intended to
                mislead, harass, or harm others.
              </li>
              <li>
                Attempt to abuse, overload, reverse-engineer, or interfere
                with the service or its underlying infrastructure.
              </li>
              <li>Use the service for any unlawful purpose.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-text">
              7. Service availability
            </h2>
            <p className="mt-3">
              CogniGraph depends on third-party AI, search, and hosting
              providers. We don&apos;t guarantee uninterrupted availability,
              and features may change, be added, or be removed as the
              product evolves.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-text">
              8. Disclaimer &amp; limitation of liability
            </h2>
            <p className="mt-3">
              CogniGraph is provided &quot;as is,&quot; without warranties of
              any kind. To the fullest extent permitted by law, we are not
              liable for any damages arising from your use of the service,
              including reliance on AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-text">
              9. Termination
            </h2>
            <p className="mt-3">
              You can stop using CogniGraph and delete your account at any
              time. We may suspend or terminate accounts that violate these
              terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-text">
              10. Changes to these terms
            </h2>
            <p className="mt-3">
              We may update these terms as CogniGraph evolves. We&apos;ll
              update the &quot;Last updated&quot; date above when we do.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-text">11. Contact</h2>
            <p className="mt-3">
              Questions about these terms? Reach us at{' '}
              <span className="text-text">willford.fx@gmail.com</span>.
            </p>
          </section>
        </div>
      </main>
    </div>
  )
}